### ISSUE TITLE
End-To-End Prototype

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#1]
The following is a list of tasks needed to build an end-to-end prototype.  The scope for this is to be able to demonstrate the most basic version of the envisioned functionality.  Consider this list as a perpetual WIP, with various bullets getting fleshed out here and in their own issues over time.

- Initialize a package
  - [x] cli allows for package initialization ([#2](https://github.com/beer-garden/bg-proto/issues/2))
- Define package and its functions via yaml
  - [x] #3
- Publish package
  - [x] cli allows publishing of a package, which involves tarring up the package directory and sending it over to the builder service ([#2](https://github.com/beer-garden/bg-proto/issues/2))
    - [x] #4
    - [x] #9
    - [x] #12 
- Use the UI to execute a function in published package
  - [x] UI lists packages --> functions.
  - [x] Task function brings up a form that is rendered based on the OpenAPI spec for the function.
- API generates function request for task manager
  - [x] #56
- Task manager routes function request to the appropriate message queue for the runner
  - [x] Task manager ingests function request, identifies the correct exchange / queue to route to, adds any additional metadata as needed (TBD), and publishes tasking message.
- Runner receives message and executes task
  - [x] Listener receives tasking message
  - [x] Container is spun up to execute function
  - [x] Message is published with results
- Task manager processes results message and records results
  - [x] #67
  - [x] API can be queried for results by task id.
  - [x] Results get displayed in the UI
