### ISSUE TITLE
UI To-Do List

### ISSUE THREAD

**Issue by obr42** [beer-garden/functionary#238]
General

- [x] #283
- [x] Consistent height for beginning of page content for all core pages (tied into breadcrumb work) (PR #294 )
- [x] No selection indicator on env select drop down when tabbing through side nav bar (PR #280 )
- [x] #285
- [ ] Dark theme!
- [ ] #339
- [x] Consistent buttons (title, type, icon vs words) ( PR #273 )
- [ ] #338
- [x] #265
- [ ] Style HTMX error pop-up
  - may need scss modal overrides for color style, see if can display html contents instead of html as a string
- [ ] Visual indicator on links to meet [WCAG standards](https://webaim.org/articles/contrast/#only:~:text=Otherwise%20two%20conditions%20must%20be%20met)
- [x] ~Style JSON Schema section with accordion/collapse~ OBE
- [ ] Add [autoprefixer](https://getbootstrap.com/docs/5.3/getting-started/download/#source-files) for CSS
- [x] Divider between breadcrumb and content  (PR #294 )
- [x] #337
- [x] #308
- [ ] #343

Nav bar

- [x] Tooltip/title at least when in icon only size so users know what they are clicking (PR #273 )
- [x] Highlight active page (PR #273 )
- [x] #274
- [x] #309

Tasking

- [x] #287
- [x] #291
- [ ] #326
- [x] #327

Functions

- [x] #310

Schedules

- [x] #311
- [x] #312
- [ ] #328 (blocked by #326)
- [ ] #341
- [ ] On create page, give contrab extra width
- [ ] On edit page, select function dropdown needs to support waveforms too #235 
    - Which package does the fn/wfv belong to? Tiered selection, modal, or list group? Filter or auto-complete?

Workflow

- [ ] Look into drag/drop for Step Table sorting
    -  Maybe use [Bootstrap-Tables](https://bootstrap-table.com/docs/extensions/reorder-rows/) extension or [follow video](https://www.youtube.com/watch?v=V-f_yYKUJo8) with sortable.js django HTMX tables
- [ ] #325

Tables

- [x] Better use of whitespace so that tables don't feel jammed against the left side (#288 )
- [x] #288
- [x] #248
- [x] #324
- [x] #335
- [ ] #340
- [ ] #342
- [x] Breadcrumb verbiage match page title (#309)
- [ ] Reduce number of text-only links, maybe we can get to clickable rows
- [ ] #336
- [ ] Indicator on filter button (narrow screen) that filters are applied
    - The way the filtering works, it does an htmx call that only loads the table contents.  So the filter button (or anything outside of the actual table) doesn't re-render when you modify the filters. `{% if filter.form.changed_data %}`

Forms

- [ ] #323

"Details" pages

- [x] #297
- [x] #302
- [x] #295
- [x] #296
- [x] #301
- [ ] Linebreak description ( `| linebreaks` ) (#302 )

Environment

- [x] #267
- [x] #303

Team

- [x] #304

Login

- [x] #322 
- [x] #315

MISC

- [ ] Admin site so we can get rid of the Bulma file?
