### ISSUE TITLE
General To-Do List

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#39]
This is just a running list of things that come to mind that need to be done.  They may be fleshed out as separate issues later, or just worked off in conjunction with other things.  We just needed a place to write things down.

- [ ] Create Task model and views
- [ ] Create worker to process results from the runners and update Task status / output.
- [ ] Refine /users endpoint response (public vs private, remove unwanted fields)
- [ ] Rethink how the teams / environments a user belongs to is retrieved (returned on user data or maybe an environments endpoint)
- [ ] Switch DB to Postgres (while maintaining SQLite option if possible).
- [ ] Restructure builder/utils.py so that docker is not required unless running the build worker
